services:
  db:
    image: mysql:latest
    container_name: clinic_db
    environment:
      MYSQL_DATABASE: php_docker
      MYSQL_USER: php_docker
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    restart: always

  www:
    build: .
    container_name: clinic_www
    volumes:
      - ./src:/var/www/html
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - db
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: clinic_phpmyadmin
    ports:
      - "8001:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      - db
    restart: always
